name: Build and publish python package

on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed

jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    name: "Publish package at PyPi"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "build"
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        id: build
        run: |
          uv build
          uv publish
      - name: "Replace KillPy with killpy"
        run: |
          sed -i 's/KillPy/killpy/g' uv.lock
          sed -i 's/KillPy/killpy/g' pyproject.toml
      - name: "Re-publish package"
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv build
          uv publish
