name: Publish beta package

on:
  workflow_run:
    workflows: ["Bump version dev"]
    types:
      - completed
  workflow_dispatch:


jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    name: "Publish package at PyPi"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "build"
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN_DEV }}
        id: build
        run: |
          uv build
          uv publish --index testpypi
